Add Node - pnpm example
actions/cache pull request #585
Opened 2021-05-12 04:53 UTC by ebeloded

2021-06-02 03:23 UTC, aminya requested changes

2021-06-02 03:23 UTC, aminya commented on examples.md
> +      path: ~/.pnpm-store
The path is different on Windows.

```suggestion
      path: |
      	 ~/.pnpm-store
         D:\.pnpm-store
```

2021-06-02 03:49 UTC, ebeloded commented on examples.md
> +      path: ~/.pnpm-store
Thank you!

2021-06-04 06:17 UTC, aminya commented on examples.md
> +      key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}```
`pnpm-store` is mostly independent of `pnpm-lock.yaml`, and restoring the store even when the lock file has changed can save a lot of time

```suggestion
      key: ${{ runner.os }}```
```

2021-06-06 00:12 UTC, Limlay approved these changes

2021-06-06 00:13 UTC, Limlay approved these changes

2021-06-06 00:15 UTC, Limlay approved these changes

2021-06-07 05:48 UTC, aminya approved these changes

2021-08-09 01:12 UTC, ebeloded commented
@aminya @Limlay 
Since last review I have added `**/node_modules` to the list of cached resources. This allows to cache artifacts that are generated during post install step. With this change the `pnpm install` script is instantaneous.

2021-08-09 01:25 UTC, aminya commented on examples.md
> +         D:\.pnpm-store
The official pnpm setup installs pnpm in the D drive. Also, it doesn't hurt if the path doesn't exist. The users can update this later.

2021-08-09 01:25 UTC, beary approved these changes

2021-08-09 01:29 UTC, beary approved these changes

2021-08-09 01:32 UTC, beary approved these changes

2021-08-09 05:51 UTC, ebeloded commented on examples.md
> +        ${{ runner.os }}
Added `-pnpm-` in cache key

2021-08-17 07:37 UTC, orta commented on examples.md
> +- [Node - Yarn](#node---pnpm)
Typo:

```suggestion
- [Node - pnpm](#node---pnpm)
```

2022-10-27 09:59 UTC, hckhanh commented
Hi @orta,
Is there any updates for this PR?

2022-10-27 14:58 UTC, orta commented
I'm afraid I don't have write access, I believe it's on @tiwarishub to make the call - looks reasonable to me though

2023-10-03 16:46 UTC, closed without merging

2024-08-13 09:19 UTC, karlhorky commented
@joshmgross what do you think about adding the changes from this PR?

I think it was closed because of lack of response from reviewers...

2024-08-13 09:25 UTC, karlhorky commented on examples.md
> +         D:\.pnpm-store
these pnpm store paths could be resolved from running `pnpm store path --silent`, as is done in `actions/setup-node`:

- https://github.com/actions/setup-node/blob/26961cf329f22f6837d5f54c3efd76b480300ace/src/cache-utils.ts#L35

2024-08-13 09:52 UTC, karlhorky commented
Probably a better version of the PR would be this, taken from [the last version in the pnpm readme](https://github.com/pnpm/action-setup/pull/131)

````markdown
## Node - pnpm

```yaml
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
```
````

2024-08-13 09:56 UTC, karlhorky commented
Opened a followup PR here:

- https://github.com/actions/cache/pull/1451