Update README to call out for version of cache
actions/cache pull request #804
Opened 2022-05-20 09:09 UTC by Phantsure

2022-05-20 17:56 UTC, bishal-pdMSFT requested changes
Does not have description. And the issue is not linked.

2022-05-20 18:05 UTC, bishal-pdMSFT commented on README.md
> +Cache version is unique for a combination of compression tools(Gzip, Zstd, etc) and the path of cache, which may differ according to runner OS as well. If two caches have different versions, then the
```suggestion
Cache version is unique for a combination of compression tool used for compression cache (Gzip, Zstd etc based on runner OS) and the path of directories being cached. If two caches have different versions, they are identified as unique cache entries. 
```

2022-05-20 18:06 UTC, Kaizamarvel approved these changes

2022-05-20 18:09 UTC, bishal-pdMSFT commented on README.md
> +Example: Below example will create 3 unique caches with same keys.
```suggestion
Example: Below example will create 3 unique caches with same keys. Ubuntu and windows runners will use different compression technique and hence create two different caches. And `build-linux` will create two different caches as the `paths` are different.
```

2022-05-26 03:56 UTC, merged

2022-05-26 19:22 UTC, Kaizamarvel approved these changes